//
// Created by cory on 4/29/25.
//

#ifndef CLAMS_CLIENTBOUND_PACKET_IDS_H
#define CLAMS_CLIENTBOUND_PACKET_IDS_H

// status state
#define STATUS_RESPONSE (0x00)
#define STATUS_PONG_RESPONSE (0x01)

// login state
#define LOGIN_DISCONNECT (0x00)
#define LOGIN_ENCRYPTION_REQUEST (0x01)
#define LOGIN_SUCCESS (0x02)
#define LOGIN_SET_COMPRESSION (0x03)
#define LOGIN_PLUGIN_REQUEST (0x04)
#define LOGIN_COOKIE_REQUEST (0x05)

// config state
#define CONFIG_COOKIE_REQUEST (0x00)
#define CONFIG_PLUGIN_MESSAGE (0x01)
#define CONFIG_DISCONNECT (0x02)
#define CONFIG_FINISH (0x03)
#define CONFIG_KEEP_ALIVE (0x04)
#define CONFIG_PING (0x05)
#define CONFIG_RESET_CHAT (0x06)
#define CONFIG_REGISTRY_DATA (0x07)
#define CONFIG_REMOVE_RESOURCE_PACK (0x08)
#define CONFIG_ADD_RESOURCE_PACK (0x09)
#define CONFIG_STORE_COOKIE (0x0a)
#define CONFIG_TRANSFER (0x0b)
#define CONFIG_FEATURE_FLAGS (0x0c)
#define CONFIG_UPDATE_TAGS (0x0d)
#define CONFIG_KNOWN_PACKS (0x0e)
#define CONFIG_CUSTOM_REPORT_DETAILS (0x0f)
#define CONFIG_SERVER_LINKS (0x10)

// play state

#endif //CLAMS_CLIENTBOUND_PACKET_IDS_H
